clc; clear; close all;
tic
syms T0 T1 T2 T3 TK HH HL X Y Z TX TY TZ u x y z z1 z2


eqns = [...
    4*cos(x + z) + 4*cos(z) + cos(x + z + z1)*(12*cos(z2) + HL*cos(TY) + HH*sin(TY)) == X; ...
    TZ == x + z + z1 & u < 2*pi & y <= pi/2; ...
    4*sin(x + z) + 4*sin(z) + sin(x + z + z1)*(12*cos(z2) + HL*cos(TY) + HH*sin(TY)) == Y; ...
    12*sin(z2) + HL*sin(TY) + 21 == Z + HH*cos(TY); ...
    TY == z2 + y*exp(u*1i); ...
    TX == 0; ...
    0 <= u; ...
    0 <= x; ...
    0 <= y; ...
    T0 == z; ...
    T1 == x; ...
    T2 == z1; ...
    T3 == z2; ...
    TK == y*exp(u*1i)];
wwwww = solve(eqns,[T0 T1 T2 T3 TK])